# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cf_sexp_c <- function(x1, x2, lscale2, magn2) {
    .Call(`_gplite_cf_sexp_c`, x1, x2, lscale2, magn2)
}

